kFriendly.UI/Models/SearchBusinessModel.cs
namespace kFriendly.UI.Models
{
    public class SearchBusinessModel
    {
        public string Term { get; set; }
        public string Location { get; set; }
        
    }
}

kFriendly.UI/Controllers/BusinessController.cs
using kFriendly.Core.Interfaces;
using kFriendly.Core.Models;
using kFriendly.Entities;
using kFriendly.Infrastructure;
using kFriendly.UI.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace kFriendly.UI.Controllers
{
    public class BusinessController : Controller
    {
        readonly IQueryBusiness queryBusiness;
        readonly IQueryGeocode queryGeocode;

        public BusinessController(IQueryBusiness queryBusiness, IQueryGeocode queryGeocode)
        {
            this.queryBusiness = queryBusiness;
            this.queryGeocode = queryGeocode;
        }

       // [HttpGet("Search")]
        public ActionResult Search()
        {
            return View(new SearchBusinessModel());
        }

        [HttpPost]
        public async Task<ActionResult> Search(string term, string location)
        {
            //ModelState.IsValid;
            //ModelState.Clear();
            KFBusinessModel allBusinesses = await queryBusiness.GetBusinessByCriteria(term, location);

           
            return View("BusinessSearchResults", allBusinesses);
        }


        //private async Task<BusinessSearchResponse> SearchBla()
        //{
        //    using (HttpClient Client = new HttpClient())
        //    {

        //        Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Credentials.API_KEY_YELP);
        //        var response = await Client.GetAsync(@"https://api.yelp.com/v3/autocomplete?latitude=33.7325566&longitude=-118.0010307&text=piz", new CancellationToken());
        //        var response2 = Client.GetAsync(@"https://api.yelp.com/v3/autocomplete?latitude=33.7325566&longitude=-118.0010307&text=piz", new CancellationToken());
        //        var data = await response.Content.ReadAsStringAsync();

        //        var jsonModel = JsonConvert.DeserializeObject<BusinessSearchResponse>(data);

        //        return jsonModel;

        //    }
        //}

        [HttpPost]
        public async Task<ActionResult> Autocomplete(string term, string latitude, string longitude)
        {
            List<string> suggestions = new List<string>();

            SearchRequest searchCriteria = new SearchRequest();

            double parsedLatitude;
            if (double.TryParse(latitude, out parsedLatitude))
            {
                searchCriteria.Latitude = parsedLatitude;
            }

            double parsedLongitude;
            if (double.TryParse(longitude, out parsedLongitude))
            {

                searchCriteria.Longitude = parsedLongitude;
            }

            // searchCriteria.Locale = locale;

            if (string.IsNullOrEmpty(term) == false)
            {
                searchCriteria.Text = term;

                suggestions = await queryBusiness.Autocomplete(searchCriteria);
            }

            return Json(suggestions, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> GetLocationFriendlyName(string latitude, string longitude)
        {
            

            string location = string.Empty;

            double parsedLatitude;
            double parsedLongitude;

            if (double.TryParse(latitude, out parsedLatitude) && double.TryParse(longitude, out parsedLongitude))
            {
                location = await queryGeocode.GetAreaName(parsedLatitude, parsedLongitude);
            }

            return Json(location, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BusinessDetails(YelpBusiness business)
        {
            // var allBusinesses = queryBusiness.GetBusinessByCriteria(criteria);

            return View(business);
        }
    }
}

kFriendly.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kFriendly.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

kFriendly.UI/Views/Business/BusinessDetails.cshtml
@model kFriendly.Entities.YelpBusiness

@{
    ViewBag.Title = "BusinessDetails";
}

<h2>Business</h2>

<div>
    <h4>Business</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Neighborhood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Neighborhood)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stars)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOpen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOpen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BusinessId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

kFriendly.UI/Views/Business/BusinessSearchResults.cshtml
@model IEnumerable<kFriendly.Core.Models.KFBusinessModel>

@{
    ViewBag.Title = "BusinessSearchResults";
}

<h2>Business</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Neighborhood)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stars)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsOpen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @Html.HiddenFor(modelItem => item.Name)
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Neighborhood)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stars)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsOpen)
        </td>
        <td>           
            @Html.ActionLink("Details", "BusinessDetails", new { business = item }) 
        </td>
    </tr>
}

</table>

kFriendly.UI/Views/Business/Search.cshtml
@model kFriendly.UI.Models.SearchBusinessModel

@{
    ViewBag.Title = "Search";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="homepage-hero" style="background-image: url(https://s3-media1.fl.yelpcdn.com/assets/srv0/yelp_large_assets/8a6cc705477a/assets/img/home/hero_photos/uteUmycsbh0UibXk-At-3A.jpg)">
        @*<div class="y-container_content">*@
        <div class="form-row h-100 justify-content-center align-items-center ">
            <div class="col-sm-4">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Find</span>
                        </div>
                        @Html.EditorFor(model => model.Term, new { htmlAttributes = new { @class = "form-control", @placeholder = "pizza, lunch, coffee" } })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Near</span>
                        </div>
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                    </div>
                </div>
            </div>

            <div class="col-sm-2">

                <div class="form-group">
                    <div class="input-group mb-3">
                        <button type="submit" class="btn btn-info">
                            <span class="oi oi-magnifying-glass"></span> Search
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    @*</div>*@

}


<script type="text/javascript" language="javascript">

    var latitude = '';
    var longitude = '';

    var getLocation = function (){

        navigator.geolocation.getCurrentPosition(function (loc) {

            latitude = loc.coords.latitude;
            longitude = loc.coords.longitude;

            $.ajax({
                dataType: "json",
                type: 'POST',
                url: '@Url.Action("GetLocationFriendlyName")',
                data: {
                    latitude: latitude,
                    longitude: longitude
                },
                success: function (data) {
                    $('#Location').val(data);
                },
                error: function (data) {
                }
            });

        })
    };


    $(document).ready(function () {

        getLocation();

        $('#Term').autocomplete({
            source: function (request, response) {
                $.ajax({
                    dataType: "json",
                    type: 'POST',
                    url: '@Url.Action("Autocomplete")',
                    data: {
                        term: request.term,
                        latitude: latitude,
                        longitude: longitude
                    },
                    success: function (data) {
                        response(data);
                    },
                    error: function (data) {
                    }
                });
            },
        });
    })

</script>

kFriendly.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

kFriendly.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

kFriendly.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

kFriendly.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KFriendly</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>


    @*<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="/Images/logo.png" width="70" height="70" class="d-inline-block align-bottom" alt="">

            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item nav-link">
                        <span class="oi oi-pencil"></span>
                        @Html.ActionLink("Write Review", "Contact", "Home")
                    </li>
                </ul>
                <ul class="navbar-nav navbar-right">
                    <li class="nav-item nav-link">
                        <span class="oi oi-person"></span>
                        @Html.ActionLink("Log In", "Search", "Business")
                    </li>
                    <li class="nav-item nav-link">
                        <span class="oi oi-plus"></span>
                        @Html.ActionLink("Sign Up", "Search", "Business")
                    </li>
                </ul>
            </div>
        </nav>*@

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="/Images/logo.png" width="70" height="70" class="d-inline-block align-bottom" alt="">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="mainMenu" class="navbar-collapse collapse">
                @*mr-auto is push to the right*@
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item nav-link">
                        <span class="oi oi-pencil"></span>
                        @Html.ActionLink("Write Review", "Contact", "Home")
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item nav-link">
                        <span class="oi oi-person"></span>
                        @Html.ActionLink("Log In", "Search", "Business")
                    </li>
                    <li class="nav-item nav-link">
                        <span class="oi oi-plus"></span>
                        @Html.ActionLink("Sign Up", "Search", "Business")
                    </li>
                </ul>
            </div>     
        </div>
    </nav>

    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="text-sm-right">&copy; @DateTime.Now.Year - KFriendly</div>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>